<div id="callMeForm" class="popup zoom-anim-dialog mfp-hide">
    <h4>Заполните форму</h4>
    <p>Мы свяжемся с Вами в рабочее время:</p>
    <form id = "callMe">
        <input type="text" placeholder="Введите имя" name = "name">
        <input type="text" placeholder="Введите e-mail *" name = "email">
        <input type="text" placeholder="Введите телефон *" name = "phone">
        <input type="submit" value="Отправить запрос">
    </form>
    <span>Мы соблюдаем ФЗ «О персональных данных» и не передаем Ваши данные третьим лицам.</span>
</div>


<div id="callMe_thanks" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Спасибо</h6>
    <p>Мы свяжемся с Вами в рабочее время.</p>
</div>
<div id="callMe_didNotWork" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Ошибка</h6>
    <p>Не отправлено по техническим причинам.</p>
</div>
<div id="notValidEmail" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Oшибка</h6>
    <p>Введите корректный e-mail.</p>
</div>
<div id="cantBeEmptyPhone" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Oшибка</h6>
    <p>Заполните поле «телефон».</p>
</div>
<div id='cantBeEmptyEmail' class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Oшибка</h6>
    <p>Заполните поле «e-mail».</p>
</div>