<form id = "sendEmail">
    <input type="text" placeholder="Введите e-mail" name = "email">
    <input type="submit" value="">
</form>
<span>Мы соблюдаем ФЗ «О персональных данных» и не передаем Ваши данные третьим лицам.</span>


<div id="notValidEmail" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Oшибка</h6>
    <p>Введите корректный e-mail.</p>
</div>

<div id='cantBeEmptyEmail' class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Oшибка</h6>
    <p>Заполните поле «e-mail».</p>
</div>

<div id="sendEmail_thanks" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Спасибо</h6>
    <p>Каталог шин отправлен по e-mail.</p>
</div>

<div id="sendEmail_error" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Ошибка</h6>
    <p>Не отправлено по техническим причинам.</p>
</div>
