<div id="sendBrochure" class="popup zoom-anim-dialog mfp-hide">
    <h4>Заполните форму</h4>
    <p>Брошюра о шине будет отправлена по e-mail:</p>
    <form id="sendBrochureData">
        <input type="text" placeholder="Введите e-mail" name="email">
        <input type="submit" value="Получить письмо">
    </form>
    <span>Мы соблюдаем ФЗ «О персональных данных» и не передаем Ваши данные третьим лицам.</span>
</div>
<div id="sendBrochure_thanks" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Спасибо</h6>
    <p>Брошюра о шине будет отправлена по e-mail.</p>
</div>
<div id="sendBrochure_error" class="popup_thanks zoom-anim-dialog mfp-hide">
    <h6>Ошибка</h6>
    <p>Не отправлено по техническим причинам.</p>
</div>