<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Крупногабаритные шины | R-GROUP — официальный дистрибьютор MICHELIN.</title>
    <meta name="description" content="Крупногабаритные шины | R-GROUP — официальный дистрибьютор MICHELIN.">
    <meta name="keywords" content="крупногабаритные шины спецтехника купить продажа michelin официальный дилер дистрибьютор Узбекистан Мишлен" />
    <link rel="icon" type="/image/png" href="/favicon.jpg" />
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/jquery-1.12.4.min.js"></script>
    <script src="/js/jquery.magnific-popup.js"></script>
    <script src="/js/script.js"></script>
</head>
<body>
<header>
    <div class="content">
        <div class="header">
            <div class="logo">
                <a href=<?=$siteSections['index'];?>>
                    <img src="/images/logo.png" alt="">
                </a>
            </div>
            <p>R-GROUP — официальный дистрибьютор <br> MICHELIN по Республике Узбекистан</p>
            <ul class="navbar">
                <li class="nav_item">
                    <a href="<?=$siteSections['index'];?>">Главная</a>
                </li>
                <li class="nav_item">
                    <a href="<?=$siteSections['company'];?>">Компания</a>
                </li>
                <li class="nav_item">
                    <a href="<?=$siteSections['catalogue'];?>">Каталог</a>
                </li>
                <li class="nav_item">
                    <a href="<?=$siteSections['contacts'];?>">Контакты</a>
                </li>
                <li class="nav_tel">
                    <a href="tel:+7 495 532 11 22">+7 495 532 11 22</a>
                </li>
            </ul>
            <a href="tel:+7 495 532 11 22" class="head_tel">+7 495 532 11 22</a>
            <a href="#" class="open_menu_btn">
                <span></span>
                <span></span>
                <span></span>
            </a>
        </div>
    </div>
</header>
