<footer>
    <div class="content">
        <div class="foo clearfix">
            <div class="foo_item">
                <span>
                    <img src="/images/1.svg" alt="">
                </span>
                <div>
                    <h6>Профессионализм</h6>
                    <p>Даем рекомендации для более эффективного управления Вашим шинным хозяйством</p>
                </div>
            </div>
            <div class="foo_item">
                <span>
                    <img src="/images/2.svg" alt="">
                </span>
                <div>
                    <h6>Доступный сервис</h6>
                    <p>Наши мобильные специалисты готовы оказать любую поддержку в любой момент.</p>
                </div>
            </div>
            <div class="foo_item">
                <span>
                    <img src="/images/3.svg" alt="">
                </span>
                <div>
                    <h6>Гибкий подход</h6>
                    <p>Предлагаем решения для конкретных условий эксплуатации на Вашем предприятии.</p>
                </div>
            </div>
        </div>
        <div class="bottom clearfix">
            <div class="left clearfix">
                <span>© 2018, R-GROUP LLC.</span>
                <a href=<?=$siteSections['privacy'];?> class="politika_btn">Политика конфиденциальности</a>
            </div>
            <div class="right">
                <p>Обращаем Ваше внимание на то, что вся предоставленная информация носит справочно-информационный характер и ни при каких условиях не является офертой, определяемой положениями статьи 435 и части 2 статьи 437 Гражданского Кодекса Российской Федерации.</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>
